### ISSUE TITLE
Bug: incorrectly highlighting inline text?

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#13]
Not sure if this is caused by a bug in highlighting inline text, but in one case, markshell highlights the whole line, while nothing has been marked as code:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/11164679/91336833-d28fa880-e7d2-11ea-8f22-fb59ae31d98b.png">

For repro, markshell https://github.com/waldekmastykarz/cli-microsoft365/blob/552d9fd2b83f8c3487e1d8b274b4965b6275ec78/docs/manual/docs/cmd/spo/site/site-add.md

**Comment by waldekmastykarz** [comment]
Still present in 0.0.6-beta2

**Comment by StfBauer** [comment]
Looked in my case always like this:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/5503835/91647365-4db6c000-ea5a-11ea-8d67-5fe55d17bfe6.png">

Might be fixed in today's nightly build.

**Comment by waldekmastykarz** [comment]
Cool! Will give it a  try

**Comment by StfBauer** [comment]
Fixed in 📦  markshell@0.0.6-beta3 - removed background.

**Comment by waldekmastykarz** [comment]
Confirmed fixed
