### ISSUE TITLE
Bug: extra empty line in a highlighted code block

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#15]
Version 0.0.6-beta2

### Actual

Highlighted code blocks have an extra empty line at the end:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/11164679/91637130-62696880-ea06-11ea-92c0-aa1fe7e61bf6.png">

### Expected

Code blocks have one empty leading and trailing line

### Repro

Markshell https://github.com/waldekmastykarz/cli-microsoft365/blob/552d9fd2b83f8c3487e1d8b274b4965b6275ec78/docs/manual/docs/cmd/spo/site/site-add.md

**Comment by StfBauer** [comment]
Yep know issue

**Comment by StfBauer** [comment]
Fixed in 0.6.0-beta3

**Comment by waldekmastykarz** [comment]
Confirmed fixed
