### ISSUE TITLE
Bug: some inline code snippets are not highlighted

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#16]
Version: 0.0.6-beta2

### Actual

<img width="424" alt="image" src="https://user-images.githubusercontent.com/11164679/91637154-96448e00-ea06-11ea-8b73-bf2d3205471c.png">

Notice how `help` is highlighted but `type` for example isn't

### Expected

All inline code snippets are correctly highlighted

### Repro

Markshell https://github.com/waldekmastykarz/cli-microsoft365/blob/552d9fd2b83f8c3487e1d8b274b4965b6275ec78/docs/manual/docs/cmd/spo/site/site-add.md

**Comment by StfBauer** [comment]
Caused by [] - reason yet unknown

**Comment by StfBauer** [comment]
Highlight fixed and background removed from default styles.

**Comment by StfBauer** [comment]
Fixed in 📦  markshell@0.0.6-beta3

**Comment by waldekmastykarz** [comment]
Confirmed fixed
