### ISSUE TITLE
Return formatted string rather than outputting to console

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#2]
Right now, the formatted markdown string is sent directly to console. This could be problematic if the package is integrated in an existing solution that manages its output differently. If the package could return the formatted markdown string as a string then the parent solution could decide itself how it wants to communicate it to users.

**Comment by StfBauer** [comment]
Would the new function `markshell.toRawContent` work?

Add it to the solution and fixed in 0.0.3.

**Comment by StfBauer** [comment]
Happy to take PRs next time.

**Comment by waldekmastykarz** [comment]
Nice! Yes, this is very helpful indeed and nice to offer both options.
