### ISSUE TITLE
Enhancement: cotrol admonition's indent

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#20]
It would be great if it was possible to control both the admonition's margin and padding separately.

Right now, when you set `before` to 0, it moves the admonition to the left without margin on padding:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/11164679/93666325-96700080-fa7d-11ea-9bcb-fdeec311bad6.png">

When you set it to `1`, it creates both a margin and a padding of 1:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/11164679/93666335-ae478480-fa7d-11ea-9e01-18c3bb4d8e2c.png">

When set to `2`, it creates both a margin and a padding of 2:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/11164679/93666345-c919f900-fa7d-11ea-8eec-c79b6db31841.png">

It would be great if it was possible to for example have a margin of 0 with a padding of 2 for a nice visual effect.

**Comment by StfBauer** [comment]
Planned feature but haven't made it in the last release.

**Comment by StfBauer** [comment]
Changes in version 1.2.0 - hope these work.

The admonitions style has now three option:
* beforeIndent - spaces before the bar aka margin left
* afterIndent - spaces before the bar aka margin right
* titleIndent - spaces before the title aka padding-left side of the title with color. 0 value also means that there won't be any.

```javascript
var styles = theme.admonitions.getStyles();
styles.indent.beforeIndent = 3;
styles.indent.afterIndent = 10;
styles.indent.titleIndent = 10;

theme.admonitions.setStyles(styles);
```

Preview:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/5503835/93714149-1c18ac80-fb61-11ea-9178-51f5fcbd0c39.png">

```javascript
var theme = markshell.getTheme();

var styles = theme.admonitions.getStyles();
styles.indent.beforeIndent = 0;
styles.indent.afterIndent = 0;
styles.indent.titleIndent = 0;

theme.admonitions.setStyles(styles);
```

**Preview:**
<img width="681" alt="image" src="https://user-images.githubusercontent.com/5503835/93714174-466a6a00-fb61-11ea-9b00-d6bcd0f8443e.png">

```javascript
// get default theme
var theme = markshell.getTheme();

var styles = theme.admonitions.getStyles();
styles.indent.beforeIndent = 1;
styles.indent.afterIndent = 3;
styles.indent.titleIndent = 2;

theme.admonitions.setStyles(styles);
```

**Preview:**

<img width="680" alt="image" src="https://user-images.githubusercontent.com/5503835/93714209-70bc2780-fb61-11ea-9d08-75fd26e6d6c5.png">

**Comment by waldekmastykarz** [comment]
Nice! Can't wait to try it out! Thank you 👏

**Comment by waldekmastykarz** [comment]
Just to check, is the black padding on the right side intended?

![image](https://user-images.githubusercontent.com/11164679/93858881-2485fa00-fcbd-11ea-8f3b-2e64a2cf4823.png)

**Comment by StfBauer** [comment]
How does your configuration look like? You can control it with the after indent. I guess I have some default values there.

**Comment by waldekmastykarz** [comment]
Ah right, totally forgot about `after`. Will have a look and get back with the results. Thanks!

**Comment by waldekmastykarz** [comment]
That does it! Thanks!
