### ISSUE TITLE
Exception: Error in Highlighted Code: RangeError: Invalid count value

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#7]
Exception `Error in Highlighted Code: RangeError: Invalid count value` is being thrown when trying to markshell MD file https://github.com/waldekmastykarz/cli-microsoft365/blob/552d9fd2b83f8c3487e1d8b274b4965b6275ec78/docs/manual/docs/cmd/spo/site/site-add.md.

Repro:

- add the .md file to samples in the project
- in the test update the reference to point to the .md file
- run `npm t` > exception

**Comment by StfBauer** [comment]
Fixed in next release. The issue was dependent on the shell window width.

**Comment by waldekmastykarz** [comment]
Fix confirmed in 0.0.6-beta2
