### ISSUE TITLE
Question: shouldn't `:` be removed when parsing DL?

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#8]
When parsing DLs in markdown, shouldn't `:` indicating `dd` be removed in the console? Current output is:

<img width="208" alt="image" src="https://user-images.githubusercontent.com/11164679/91335964-79734500-e7d1-11ea-8b3a-bfe885bd4e03.png">

which looks kind of odd.

**Comment by StfBauer** [comment]
Is fixed now after rewriting the token handling. Must have been a side effect from syntax highlighting. 😜

**Comment by waldekmastykarz** [comment]
Fix confirmed in 0.0.6-beta2
